### ISSUE TITLE
building website fails with LoadError about webrick

### ISSUE THREAD

**Issue by ForrestTrepte** [modelica/fmi-standard.org#402]
I am running Windows with hash 2911945 of fmi-standard.org. When I tried building the web site using the instructions at https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#building-the-website-locally to run the command `docker run --volume="%cd%:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll jekyll serve`, I received the following error message:

```
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from /usr/gem/bin/jekyll:25:in `load'
        from /usr/gem/bin/jekyll:25:in `<main>'
```

Any ideas what I may be doing wrong? It looks a little similar to [this issue](https://github.com/jekyll/jekyll/issues/8523) but I don't understand enough about Jekyll to understand.

**Comment by ForrestTrepte** [comment]
Thanks, @t-sommer! That fixed it for me.
